version: '2.1'
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d/
      - ./build:/usr/share/nginx/html/
    ports:
      - '3100:80'
    restart: always
